### ISSUE TITLE
QLoRA Finetune Example

### ISSUE THREAD

**Issue by sr5434** [erfanzar/EasyDeL#103]
Can you post an example of how to fine-tune a llm with 4-bit QLoRA on a TPU? Thanks for any help you can provide.

**Comment by erfanzar** [comment]
Yes soon ill add that but what kinda device you are using? Tpu/gpu/xpu?

**Comment by sr5434** [comment]
I’m using TPU v3

**Comment by sr5434** [comment]
I just change the Params dtype right?

**Comment by erfanzar** [comment]
you have to use bits=4 or 8 and pass lora config to Xrapture Module

**Comment by sr5434** [comment]
Ok, thanks

**Comment by sr5434** [comment]
There doesn’t appear to be an argument for bits

**Comment by sr5434** [comment]
Nvm

**Comment by erfanzar** [comment]
> Nvm

You have to change them inside model config

You can read docs for that or just see examples

**Comment by sr5434** [comment]
Ok, thanks. Also, is there a way to save just the LoRA adapter in the HuggingFace format after training?

**Comment by sr5434** [comment]
Ok, thanks.
