### ISSUE TITLE
Training in kaggle's TPU is failing

### ISSUE THREAD

**Issue by saidineshpola** [erfanzar/EasyDeL#117]
**Describe the bug**
ValueError: Memory kinds passed to jax.jit does not match memory kind on the respective arg. Got pjit memory kind: tpu_hbm, arg memory kind: None for arg shape: float16[51200]

**To Reproduce**
```
!pip install datasets
!pip install git+https://github.com/erfanzar/EasyDeL.git
!pip install jax[tpu]==0.4.21 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html

import os
# disable Weights and Biases
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    #BitsAndBytesConfig,
    HfArgumentParser,
    AutoTokenizer,
    GenerationConfig
)
from tqdm import tqdm
import time
import pandas as pd
import numpy as np
from functools import partial
from transformers import set_seed
from ast import literal_eval
# from huggingface_hub import interpreter_login

# interpreter_login()
IS_TPU=True

import jax.numpy
from EasyDel import (
    TrainArguments,
    CausalLanguageModelTrainer,
    AutoEasyDelModelForCausalLM,
    EasyDelOptimizers,
    EasyDelSchedulers,
    EasyDelGradientCheckPointers
)
from datasets import load_dataset
import flax
from jax import numpy as jnp
from transformers import AutoTokenizer
print('Import Successfull')

# disable Weights and Biases
os.environ['WANDB_DISABLED']="true"
huggingface_repo_id_or_path = "microsoft/phi-2"

model, params = AutoEasyDelModelForCausalLM.from_pretrained(huggingface_repo_id_or_path, )


max_length = 2048
tokenizer = AutoTokenizer.from_pretrained(
    huggingface_repo_id_or_path,
    trust_remote_code=True
)
tokenizer.pad_token = tokenizer.eos_token
configs_to_initialize_model_class = {
    "config": model.config,
    "dtype": jnp.bfloat16,
    "param_dtype": jnp.bfloat16,
    "input_shape": (1, 1)
}

train_arguments = TrainArguments(
    model_class=type(model),
    model_name="my_first_model_to_train_using_easydel",
    num_train_epochs=3,
    configs_to_initialize_model_class=configs_to_initialize_model_class,
    learning_rate=5e-5,
    learning_rate_end=1e-6,
    optimizer=EasyDelOptimizers.ADAMW,  # "adamw", "lion", "adafactor" are supported
    scheduler=EasyDelSchedulers.LINEAR,
    # "linear","cosine", "none" ,"warm_up_cosine" and "warm_up_linear"  are supported
    weight_decay=0.01,
    total_batch_size=64,
    max_training_steps=None,  # None to let trainer Decide
    do_train=True,
    do_eval=False,  # it's optional but supported 
    backend="tpu",  # default backed is set to cpu, so you must define you want to use tpu cpu or gpu
    max_length=max_length,  # Note that you have to change this in the model config too
    gradient_checkpointing=EasyDelGradientCheckPointers.NOTHING_SAVEABLE,
    sharding_array=(1, 1, 1, -1),  # the way to shard model across gpu,cpu or TPUs using sharding array (1, 1, 1, -1)
    # everything training will be in sequence and model parallel automatic and share data between devices
    use_pjit_attention_force=False,
    remove_ckpt_after_load=True,
    gradient_accumulation_steps=8,
    loss_re_mat="",
    dtype=jnp.bfloat16
)


# def ultra_chat_prompting_process(
#         data_chunk
# ):
#     user_part = [
#         chunk["content"] for chunk in data_chunk["messages"] if chunk["role"] == "user"
#     ]
#     assistant_part = [
#         chunk["content"] for chunk in data_chunk["messages"] if chunk["role"] == "assistant"
#     ]

#     prompt = ""

#     for uc, ac in zip(user_part, assistant_part):
#         prompt += f"<|user|>\n{uc}</s>\n<|assistant|>\n{ac}</s>\n"

#     return {"prompt": prompt}


# tokenization_process = lambda data_chunk: tokenizer(
#     data_chunk["prompt"],
#     add_special_tokens=False,
#     max_length=max_length,
#     padding="max_length"
# )

# dataset = load_dataset("HuggingFaceH4/ultrachat_200k")
# dataset_train = dataset["train_gen"].map(ultra_chat_prompting_process, num_proc=12)
# dataset_train = dataset_train.map(
#     tokenization_process,
#     num_proc=12,
#     remove_columns=dataset_train.column_names
# )

# you can do the same for evaluation process dataset

trainer = CausalLanguageModelTrainer(
    train_arguments,
    train_dataset,
    checkpoint_path=None
)

output = trainer.train(flax.core.FrozenDict({"params": params}))
print(f"Hey ! , here's where your model saved {output.checkpoint_path}") 
```
Steps to reproduce the behavior

**Comment by erfanzar** [comment]
hello, and thanks for using EasyDeL!
your code seems like to have some problems, ill try to run your code but make sure your using right version of jax
```shell
pip install jax[tpu]==0.21.0 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```
### 0.21.0 does not exists we are currently on 0.4.25 / 26

**Comment by saidineshpola** [comment]
By bad i forgot to add 0.4.21
The default jax's 0.4.25 version in Kaggle is giving import errors so I used old one

**Comment by erfanzar** [comment]
cool but as I have shown in examples in the case of using Kaggle you should upgrade tensorflow too cause the newer JAX version needs newer TPU software and by upgrading tensorflow those TPU errors will be fixed

**Comment by erfanzar** [comment]
there are many tricks and things you must consider in the case of working with EasyDeL like training arguments like max_sequence_length, parition_spec, and ... i have modified your code, and here's the working version

```shell
pip install datasets
pip install git+https://github.com/erfanzar/EasyDeL.git
pip install jax[tpu]==0.4.23 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
pip install tensorflow -U
```

```python

import os
# disable Weights and Biases
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    #BitsAndBytesConfig,
    HfArgumentParser,
    AutoTokenizer,
    GenerationConfig
)
from tqdm import tqdm
import time
import pandas as pd
import numpy as np
from functools import partial
from transformers import set_seed
from ast import literal_eval
# from huggingface_hub import interpreter_login

# interpreter_login()
IS_TPU=True

import jax.numpy
from EasyDel import (
    TrainArguments,
    CausalLanguageModelTrainer,
    AutoEasyDelModelForCausalLM,
    EasyDelOptimizers,
    EasyDelSchedulers,
    EasyDelGradientCheckPointers
)
from datasets import load_dataset
import flax
from jax import numpy as jnp
from transformers import AutoTokenizer



# disable Weights and Biases
os.environ['WANDB_DISABLED']="true"
huggingface_repo_id_or_path = "microsoft/phi-2"

model, params = AutoEasyDelModelForCausalLM.from_pretrained(huggingface_repo_id_or_path, )


max_length = 2048
tokenizer = AutoTokenizer.from_pretrained(
    huggingface_repo_id_or_path,
    trust_remote_code=True
)
tokenizer.pad_token = tokenizer.eos_token
configs_to_initialize_model_class = {
    "config": model.config,
    "dtype": jnp.bfloat16,
    "param_dtype": jnp.bfloat16,
    "input_shape": (1, 1)
}

train_arguments = TrainArguments(
    model_class=type(model),
    model_name="my_first_model_to_train_using_easydel",
    num_train_epochs=3,
    configs_to_initialize_model_class=configs_to_initialize_model_class,
    learning_rate=5e-5,
    learning_rate_end=1e-6,
    max_sequence_length=max_length,
    optimizer=EasyDelOptimizers.ADAMW,  # "adamw", "lion", "adafactor" are supported
    scheduler=EasyDelSchedulers.LINEAR,
    # "linear","cosine", "none" ,"warm_up_cosine" and "warm_up_linear"  are supported
    weight_decay=0.01,
    total_batch_size=8,
    max_training_steps=None,  # None to let trainer Decide
    do_train=True,
    do_eval=False,  # it's optional but supported 
    backend="tpu",  # default backed is set to cpu, so you must define you want to use tpu cpu or gpu
    max_length=max_length,  # Note that you have to change this in the model config too
    gradient_checkpointing=EasyDelGradientCheckPointers.NOTHING_SAVEABLE,
    sharding_array=(1, 1, 1, -1),  # the way to shard model across gpu,cpu or TPUs using sharding array (1, 1, 1, -1)
    # everything training will be in sequence and model parallel automatic and share data between devices
    use_pjit_attention_force=False,
    remove_ckpt_after_load=True,
    gradient_accumulation_steps=1,
    loss_re_mat="",
    dtype=jnp.bfloat16,
    use_wandb=False # This disable WANB usage
)


def ultra_chat_prompting_process(
        data_chunk
):
    user_part = [
        chunk["content"] for chunk in data_chunk["messages"] if chunk["role"] == "user"
    ]
    assistant_part = [
        chunk["content"] for chunk in data_chunk["messages"] if chunk["role"] == "assistant"
    ]

    prompt = ""

    for uc, ac in zip(user_part, assistant_part):
        prompt += f"<|user|>\n{uc}</s>\n<|assistant|>\n{ac}</s>\n"

    return {"prompt": prompt}


tokenization_process = lambda data_chunk: tokenizer(
    data_chunk["prompt"],
    add_special_tokens=False,
    max_length=max_length,
    padding="max_length"
)

dataset = load_dataset("HuggingFaceH4/ultrachat_200k")
dataset_train = dataset["train_gen"].map(ultra_chat_prompting_process, num_proc=12)
dataset_train = dataset_train.map(
    tokenization_process,
    num_proc=12,
    remove_columns=dataset_train.column_names
)

# you can do the same for evaluation process dataset

trainer = CausalLanguageModelTrainer(
    train_arguments,
    dataset_train,
    checkpoint_path=None
)

output = trainer.train(flax.core.FrozenDict({"params": params}))
print(f"Hey ! , here's where your model saved {output.checkpoint_path}") 
```

**Comment by saidineshpola** [comment]
The training is failed again with following error for phi-2
`# you can do the same for evaluation process dataset
---> 77 trainer = CausalLanguageModelTrainer(
     78     train_arguments,
     79     train_dataset,
     80     checkpoint_path=None
     81 )
     83 output = trainer.train(flax.core.FrozenDict({"params": params}))
     84 print(f"Hey ! , here's where your model saved {output.checkpoint_path}")

File /usr/local/lib/python3.10/site-packages/EasyDel/trainer/base_trainer.py:144, in BaseTrainer.__init__(self, arguments, dataset_train, dataset_eval, finetune, checkpoint_path, _do_init_fns)
    138         prefix_print(
    139             "Warning",
    140             "In case of using `finetune = True` and Passing `checkpoint_path = None`"
    141             " you should pass parameters in train function"
    142         )
    143 if _do_init_fns:
--> 144     self.initialize_trainer_utils()
    145 else:
    146     prefix_print(
    147         "Warning",
    148         "you have set `_do_init_fns = False` so function will not me initialized you have "
    149         f"to do in manually (simply with `trainer.initialize_trainer_utils()` )"
    150     )

File /usr/local/lib/python3.10/site-packages/EasyDel/trainer/base_trainer.py:203, in BaseTrainer.initialize_trainer_utils(self)
    200 self.timer.log(["configure dataloaders"])
    202 self.timer("configure Model, Optimizer, Scheduler and Config").start()
--> 203 model_configurations = self.configure_model()
    204 model = model_configurations.model
    205 tx = model_configurations.tx

File /usr/local/lib/python3.10/site-packages/EasyDel/trainer/base_trainer.py:352, in BaseTrainer.configure_model(self)
    347         config = None
    348         warnings.warn(
    349             "Config is being set to None due to not detecting Model Configuration from taken Model "
    350             "this will cause errors later."
    351         )
--> 352 tx, scheduler = self.arguments.get_optimizer_and_scheduler(self.max_training_steps)
    353 return TrainerConfigureModelFuncOutput(
    354     model=model,
    355     tx=tx,
    356     scheduler=scheduler,
    357     config=config
    358 )

File /usr/local/lib/python3.10/site-packages/EasyDel/trainer/training_configurations.py:449, in TrainArguments.get_optimizer_and_scheduler(self, steps)
    444 def get_optimizer_and_scheduler(
    445         self,
    446         steps: int | None = None
    447 ):
    448     self.optimizer_kwargs["steps"] = steps or self.optimizer_kwargs["steps"]
--> 449     return get_optimizer_and_scheduler(
    450         **self.optimizer_kwargs
    451     )

File /usr/local/lib/python3.10/site-packages/EasyDel/etils/auto_tx.py:134, in get_optimizer_and_scheduler(optimizer, scheduler, steps, learning_rate, learning_rate_end, gradient_accumulation_steps, extra_optimizer_kwargs, weight_decay, warmup_steps)
    132 elif optimizer == EasyDelOptimizers.ADAMW:
    133     if scheduler == EasyDelSchedulers.LINEAR:
--> 134         tx, sc = fjformer.optimizers.get_adamw_with_linear_scheduler(
    135             learning_rate_start=learning_rate,
    136             learning_rate_end=learning_rate_end,
    137             steps=steps,
    138             gradient_accumulation_steps=gradient_accumulation_steps,
    139             **extra_optimizer_kwargs
    140         )
    141     elif scheduler == EasyDelSchedulers.COSINE:
    142         tx, sc = fjformer.optimizers.get_adamw_with_cosine_scheduler(
    143             learning_rate=learning_rate,
    144             gradient_accumulation_steps=gradient_accumulation_steps,
   (...)
    147             **extra_optimizer_kwargs
    148         )

File /usr/local/lib/python3.10/site-packages/fjformer/optimizers/adamw.py:83, in get_adamw_with_linear_scheduler(steps, learning_rate_start, learning_rate_end, b1, b2, eps, eps_root, weight_decay, gradient_accumulation_steps, mu_dtype)
     56 def get_adamw_with_linear_scheduler(
     57         steps: int,
     58         learning_rate_start: float = 5e-5,
   (...)
     67 
     68 ):
     69     """
     70 
     71     :param gradient_accumulation_steps:
   (...)
     81     :return: Optimizer and Scheduler
     82     """
---> 83     scheduler = optax.linear_schedule(
     84         init_value=learning_rate_start,
     85         end_value=learning_rate_end,
     86         transition_steps=steps
     87     )
     88     tx = optax.chain(
     89         optax.scale_by_adam(
     90             b1=b1,
   (...)
    100         optax.scale(-1)
    101     )
    102     if gradient_accumulation_steps > 1:

File /usr/local/lib/python3.10/site-packages/optax/schedules/_schedule.py:97, in linear_schedule(init_value, end_value, transition_steps, transition_begin)
     91 def linear_schedule(
     92     init_value: chex.Scalar,
     93     end_value: chex.Scalar,
     94     transition_steps: int,
     95     transition_begin: int = 0
     96 ) -> base.Schedule:
---> 97   return polynomial_schedule(
     98       init_value=init_value, end_value=end_value, power=1,
     99       transition_steps=transition_steps, transition_begin=transition_begin)

File /usr/local/lib/python3.10/site-packages/optax/schedules/_schedule.py:71, in polynomial_schedule(init_value, end_value, power, transition_steps, transition_begin)
     47 def polynomial_schedule(
     48     init_value: chex.Scalar,
     49     end_value: chex.Scalar,
   (...)
     52     transition_begin: int = 0
     53 ) -> base.Schedule:
     54   """Constructs a schedule with polynomial transition from init to end value.
     55 
     56   Args:
   (...)
     69     schedule: A function that maps step counts to values.
     70   """
---> 71   if transition_steps <= 0:
     72     logging.info(
     73         'A polynomial schedule was set with a non-positive `transition_steps` '
     74         'value; this results in a constant schedule with value `init_value`.')
     75     return lambda count: init_value

TypeError: '<=' not supported between instances of 'NoneType' and 'int'`

**Comment by saidineshpola** [comment]
Thanks for the quick resolution over the weekend.
