### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by mohammad0081** [erfanzar/EasyDeL#150]
**Describe the bug**

Hello EasyDel team 
I installed easydel on colab and after it, i attempted to import its necessary classes and functions for fine-tuning task
i faced these errors after importing : 

> import jax.numpy as jnp
from easydel import (
    TrainArguments,
    CausalLanguageModelTrainer,
    AutoEasyDeLModelForCausalLM,
    EasyDeLOptimizers,
    EasyDeLSchedulers,
    EasyDeLGradientCheckPointers
)

and the output errors were : 

> AttributeError                            Traceback (most recent call last)
[<ipython-input-3-5881168cd0e8>](https://localhost:8080/#) in <cell line: 2>()
      1 import jax.numpy as jnp
----> 2 from easydel import (
      3     TrainArguments,
      4     CausalLanguageModelTrainer,
      5     AutoEasyDeLModelForCausalLM,

> 16 frames
[/usr/local/lib/python3.10/dist-packages/easydel/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .serve import (
      2     EasyServe as EasyServe,
      3     EasyServeConfig as EasyServeConfig,
      4     LLMBaseReq as LLMBaseReq,
      5     EasyClient as EasyClient,

> [/usr/local/lib/python3.10/dist-packages/easydel/serve/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .jax_serve import JAXServer, JAXServerConfig
      2 from .torch_serve import PyTorchServer, PyTorchServerConfig
      3 from .utils import ChatRequest, InstructRequest
      4 from .gradio_user_interface_base import GradioUserInference
      5 from .utils import create_generate_function

> [/usr/local/lib/python3.10/dist-packages/easydel/serve/jax_serve.py](https://localhost:8080/#) in <module>
     13 import uvicorn
     14 from fastapi import FastAPI
---> 15 from fjformer import make_shard_and_gather_fns, match_partition_rules, with_sharding_constraint
     16 
     17 from ..etils.etils import get_logger

> [/usr/local/lib/python3.10/dist-packages/fjformer/__init__.py](https://localhost:8080/#) in <module>
     66 
     67 from . import pallas_operations as pallas_operations
---> 68 from . import optimizers as optimizers
     69 from . import linen as linen
     70 

> [/usr/local/lib/python3.10/dist-packages/fjformer/optimizers/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .adamw import (
      2     get_adamw_with_cosine_scheduler as get_adamw_with_cosine_scheduler,
      3     get_adamw_with_warm_up_cosine_scheduler as get_adamw_with_warm_up_cosine_scheduler,
      4     get_adamw_with_warmup_linear_scheduler as get_adamw_with_warmup_linear_scheduler,
      5     get_adamw_with_linear_scheduler as get_adamw_with_linear_scheduler

> [/usr/local/lib/python3.10/dist-packages/fjformer/optimizers/adamw.py](https://localhost:8080/#) in <module>
      1 from typing import Optional
      2 import chex
----> 3 import optax
      4 
      5 

> [/usr/local/lib/python3.10/dist-packages/optax/__init__.py](https://localhost:8080/#) in <module>
     15 """Optax: composable gradient processing and optimization, in JAX."""
     16 
---> 17 from optax import contrib
     18 from optax import losses
     19 from optax import monte_carlo

> [/usr/local/lib/python3.10/dist-packages/optax/contrib/__init__.py](https://localhost:8080/#) in <module>
     19 from optax.contrib.complex_valued import split_real_and_imaginary
     20 from optax.contrib.complex_valued import SplitRealAndImaginaryState
---> 21 from optax.contrib.dadapt_adamw import dadapt_adamw
     22 from optax.contrib.dadapt_adamw import DAdaptAdamWState
     23 from optax.contrib.mechanic import MechanicState

> [/usr/local/lib/python3.10/dist-packages/optax/contrib/dadapt_adamw.py](https://localhost:8080/#) in <module>
     25 from optax import tree_utils
     26 from optax._src import base
---> 27 from optax._src import utils
     28 
     29 

> [/usr/local/lib/python3.10/dist-packages/optax/_src/utils.py](https://localhost:8080/#) in <module>
     20 import jax
     21 import jax.numpy as jnp
---> 22 import jax.scipy.stats.norm as multivariate_normal
     23 
     24 from optax._src import linear_algebra

> [/usr/local/lib/python3.10/dist-packages/jax/scipy/stats/__init__.py](https://localhost:8080/#) in <module>
     16 # See PEP 484 & https://github.com/google/jax/issues/7570
     17 
---> 18 from jax.scipy.stats import bernoulli as bernoulli
     19 from jax.scipy.stats import beta as beta
     20 from jax.scipy.stats import binom as binom

> [/usr/local/lib/python3.10/dist-packages/jax/scipy/stats/bernoulli.py](https://localhost:8080/#) in <module>
     16 # See PEP 484 & https://github.com/google/jax/issues/7570
     17 
---> 18 from jax._src.scipy.stats.bernoulli import (
     19   logpmf as logpmf,
     20   pmf as pmf,

> [/usr/local/lib/python3.10/dist-packages/jax/_src/scipy/stats/bernoulli.py](https://localhost:8080/#) in <module>
     14 
     15 
---> 16 import scipy.stats as osp_stats
     17 
     18 from jax import lax

> [/usr/local/lib/python3.10/dist-packages/scipy/stats/__init__.py](https://localhost:8080/#) in <module>
    483 from ._warnings_errors import (ConstantInputWarning, NearConstantInputWarning,
    484                                DegenerateDataWarning, FitError)
--> 485 from ._stats_py import *
    486 from ._variation import variation
    487 from .distributions import *

> [/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py](https://localhost:8080/#) in <module>
     35 from numpy import array, asarray, ma
     36 from numpy.lib import NumpyVersion
---> 37 from numpy.testing import suppress_warnings
     38 
     39 from scipy.spatial.distance import cdist

> [/usr/local/lib/python3.10/dist-packages/numpy/testing/__init__.py](https://localhost:8080/#) in <module>
      9 
     10 from . import _private
---> 11 from ._private.utils import *
     12 from ._private.utils import (_assert_valid_refcount, _gen_alignment_data)
     13 from ._private import extbuild

> [/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py](https://localhost:8080/#) in <module>
     55 IS_PYSTON = hasattr(sys, "pyston_version_info")
     56 HAS_REFCOUNT = getattr(sys, 'getrefcount', None) is not None and not IS_PYSTON
---> 57 HAS_LAPACK64 = numpy.linalg._umath_linalg._ilp64
     58 
     59 _OLD_PROMOTION = lambda: np._get_promotion_state() == 'legacy'

> AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'

**Comment by erfanzar** [comment]
hi and thank you for using Easydel, there's no team behind Easydel it's just me and two dear contributors :)

AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'  error reference to numpy cache files which means you have updated your numpy version

Please just restart your session it will be fixed.
