### ISSUE TITLE
Logging into wandb.ai

### ISSUE THREAD

**Issue by mohammad0081** [erfanzar/EasyDeL#157]
hello again . i tried to run the trainer.train() function but i faced this logging warning, i gave no clue what is wandb.ai website is . is it necessary to sign up to this website for training a simple model ?

trainer = CausalLanguageModelTrainer(
    train_arguments,
    dataset_train,
    checkpoint_path=None
)

output = trainer.train(flax.core.FrozenDict({"params": params}))

-----------------------------------------------------------
warnings : 
Warning : In case of using `finetune = True` and Passing `checkpoint_path = None` you should pass parameters in train function
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

**Comment by erfanzar** [comment]
Hi

Use 
'''
!wanb login <token>
'''

**Comment by erfanzar** [comment]
And you can also turn wandb logging off in arguments
