### ISSUE TITLE
How to do sequence classification training ?

### ISSUE THREAD

**Issue by sparsh35** [erfanzar/EasyDeL#169]
**Describe the bug**
I want to train a reward model using Easydel with sequence classification. The classifier has been implemented in the Flax sequence classifier classes for each model, but is there any way to load a model to directly with sequence classifier and train it
**To Reproduce**
Steps to reproduce the behavior

**Comment by erfanzar** [comment]
hi
that's not supported at the moment, but i guess ill support that in next 24 hour

**Comment by sparsh35** [comment]
I am also thinking of implementing Online DPO trainer with EasyDel, with a little bit of your support if you are interested. 
It can be comparable with PPO as per paper from Deepmind, the biggest bottleneck I would be in generation of completitions during training.

**Comment by erfanzar** [comment]
Yes seems cool to me 
If u needed any helps u can dm me in discord

**Comment by erfanzar** [comment]
@sparsh35 SequenceClassificationTrainer is added
