### ISSUE TITLE
Examples and Docs to demonstrate running inferencing using Llama-3.2-1b or 3b models on TPU V4

### ISSUE THREAD

**Issue by rakesh010101** [erfanzar/EasyDeL#176]
There is a growing need within the ML community to perform efficient model inference using high-performance Llama models, such as Llama 3.2 (1B or 3B parameters), on Google TPU V4 hardware. However, significant gaps exist in the support ecosystem for executing Llama 3.2 model inference on TPUs. Specifically:

Hugging Face transformers library does not provide native TPU support for model inference.
Alternative libraries for TPU compatibility with Llama models are also largely unavailable, creating substantial friction in deploying these models at scale.

**Comment by erfanzar** [comment]
Thanks for raising this interest in TPU inference! 

For running inference on TPU V4, here's what you need to know:

1. This repo already supports fast inference on TPUs through vInference implementation
2. For optimal TPU V4 performance, you'll want to:
   - Use JAX/Flax for TPU-native execution
   - Enable XLA optimizations
   - Configure the right configs for TPU pod topology

Would you mind sharing your specific use case and performance requirements? That would help us provide more targeted guidance for your implementation.

> [!note]
> ill add more examples and better docs for vInference soon.
