### ISSUE TITLE
TypeError: __call__() takes from 2 to 9 positional arguments but 10 were given

### ISSUE THREAD

**Issue by JinSeoungwoo** [erfanzar/EasyDeL#31]
Below is the code I used for making train_data 

```python
train_data = dataset.map(
        lambda x:tokenizer(generate_prompt(x),max_length=4096,padding='max_length',add_special_tokens=False),
        remove_columns=dataset.column_names,
    )
```

Error :
```
  File "/usr/local/lib/python3.8/dist-packages/EasyDel/trainer/fsdp_train.py", line 409, in train
    sharded_train_state_, loss, accuracy = self.sharded_train_step_fn(sharded_train_state_,
  File "/usr/local/lib/python3.8/dist-packages/EasyDel/trainer/fsdp_train.py", line 312, in fsdp_train_step_
    (loss__, accuracy__), grad = grad_fn(state.params)
  File "/usr/local/lib/python3.8/dist-packages/EasyDel/trainer/fsdp_train.py", line 303, in calculate_loss
    logits = state.apply_fn(params=params, **batch,
  File "/usr/local/lib/python3.8/dist-packages/EasyDel/modules/mistral/modelling_mistral_flax.py", line 565, in __call__
    outputs = self.module.apply(
TypeError: __call__() takes from 2 to 9 positional arguments but 10 were given
```

and also there is a o_proj error in mistral

**Comment by erfanzar** [comment]
make sure that `generate_prompt(x)` have to return string

**Comment by JinSeoungwoo** [comment]
> make sure that `generate_prompt(x)` have to return string

generate_prompt return string

```python
def generate_prompt(data_point):
    full_prompt = prompter.generate_prompt(
        data_point["instruction"],
        data_point["input"],
        data_point["output"],
    )
    return full_prompt
```

I think 

```python
outputs = self.module.apply(
            inputs,
            jnp.array(input_ids, dtype="i4"),
            jnp.array(attention_mask, dtype="i4"),
            jnp.array(position_ids, dtype="i4"),
            not train,
            None,
            False,
            output_attentions,
            output_hidden_states,
            return_dict,
            rngs=rng_s,
            mutable=mutable,
        )
```
I think this code from modelling_mistral_flax.py is problem

**Comment by JinSeoungwoo** [comment]
> > make sure that `generate_prompt(x)` have to return string
> 
> generate_prompt return string
> 
> ```python
> def generate_prompt(data_point):
>     full_prompt = prompter.generate_prompt(
>         data_point["instruction"],
>         data_point["input"],
>         data_point["output"],
>     )
>     return full_prompt
> ```
> 
> I think
> 
> ```python
> outputs = self.module.apply(
>             inputs,
>             jnp.array(input_ids, dtype="i4"),
>             jnp.array(attention_mask, dtype="i4"),
>             jnp.array(position_ids, dtype="i4"),
>             not train,
>             None,
>             False,
>             output_attentions,
>             output_hidden_states,
>             return_dict,
>             rngs=rng_s,
>             mutable=mutable,
>         )
> ```
> 
> this code from modelling_mistral_flax.py is problem

removed None and it looks working. but Initializer expected to generate shape (1024, 4096) but got shape (4096, 1024) instead for parameter "kernel" in "/model/layers/remat(0)/self_attn/k_proj"

**Comment by erfanzar** [comment]
ill fix that in next commit

**Comment by erfanzar** [comment]
Fixed <3

**Comment by Mokocoder** [comment]
> Fixed <3 please remove the code you have edited clone the repo or install it with
> 
> ```shell
> pip install git+https://github.com/erfanzar/EasyDeL
> ```
> 
> and transform weights again

Thank you! It worked

**Comment by JinSeoungwoo** [comment]
> Fixed <3 please remove the code you have edited clone the repo or install it with
> 
> ```shell
> pip install git+https://github.com/erfanzar/EasyDeL
> ```
> 
> and transform weights again

Does transform weights again mean I need to remove the weights from the model I previously transformed?, and if so, where are the weights stored?

**Comment by JinSeoungwoo** [comment]
I'm currently finetuning mistral with v3-8
LR 2.5e-5
Mini batch 4
Gradient accumulation steps 32
Sequence length 768

And I felt something is wrong
![SmartSelect_20231007_181255_Chrome](https://github.com/erfanzar/EasyDeL/assets/145985028/de1312b1-fa63-43cb-b463-ed585ea46270)
