### ISSUE TITLE
Training on TPU pod

### ISSUE THREAD

**Issue by JinSeoungwoo** [erfanzar/EasyDeL#34]
Can I train using TPUv3-32 pod?

**Comment by JinSeoungwoo** [comment]
Also, I want to train mistral with attention_sinks method is it possible?

**Comment by JinSeoungwoo** [comment]
> yes for sure,
> can you tell me which platform you using to train your model on so i can give you step by step example

I'm using gcp right now

**Comment by erfanzar** [comment]
actually the normal code for training should work just fine but you can use custom mesh size of
1,-1,1 or 2,-1,1

**Comment by JinSeoungwoo** [comment]
> actually the normal code for training should work just fine but you can use custom mesh size of 1,-1,1 or 2,-1,1

I saw https://cloud.google.com/tpu/docs/jax-pods?hl=ko in the TPU POD documentation, can I do the same with EasyDel?

**Comment by erfanzar** [comment]
I guess EasyDel Automatically runs the code across all the available devices but yes you have to run that like this

``` shell
gcloud compute tpus tpu-vm ssh tpu-name \
  --zone=us-central2-b \
  --worker=all \
  --command="python3 example.py"
```
make sure to install the jax and jaxlib version >=0.4.10

```shell
  gcloud compute tpus tpu-vm ssh tpu-name \
  --zone=us-central2-b --worker=all --command="pip install \
  --upgrade 'jax[tpu]>0.4.10' \
  -f https://storage.googleapis.com/jax-releases/libtpu_releases.html"
```

I gueese there's a bug in the mistral model and i suggest you don't train your models till I fix that (10~18 hours)

**Comment by JinSeoungwoo** [comment]
> I guess EasyDel Automatically runs the code across all the available devices but yes you have to run that like this
> 
> ``` shell
> gcloud compute tpus tpu-vm ssh tpu-name \
>   --zone=us-central2-b \
>   --worker=all \
>   --command="python3 example.py"
> ```
> make sure to install the jax and jaxlib version >=0.4.10
> 
> ```shell
>   gcloud compute tpus tpu-vm ssh tpu-name \
>   --zone=us-central2-b --worker=all --command="pip install \
>   --upgrade 'jax[tpu]>0.4.10' \
>   -f https://storage.googleapis.com/jax-releases/libtpu_releases.html"
> ```
> 
> I gueese there's a bug in the mistral model and i suggest you don't train your models till I fix that (10~18 hours)

I've tried a lot, but after a certain number of steps, the accuracy drops dramatically. Is it possible that I'm setting the parameters incorrectly? Or is it related to a bug?

**Comment by erfanzar** [comment]
yes that's related to the bug

**Comment by JinSeoungwoo** [comment]
> yes that's related to the bug

Oh.. I thought I was setting it up wrong until now. I'll have to do the training after the bug is fixed. Thanks for the fix!

**Comment by JinSeoungwoo** [comment]
> fix <3

Thnks for the fix but when I tried to run code on pod an error occurred :

```
Traceback (most recent call last):
  File "/root/tune.py", line 249, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/tune.py", line 234, in main
    trainer = CausalLMTrainer(train_args,
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/trainer/fsdp_train.py", line 138, in __init__
    self.init_functions()
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/trainer/fsdp_train.py", line 201, in init_functions
    funcs = self.configure_functions()
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/trainer/fsdp_train.py", line 314, in configure_functions
    train_state_shape = jax.eval_shape(init_fn)
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/trainer/fsdp_train.py", line 268, in init_fn
    params__ = self.model.init_weights(jax.random.PRNGKey(0), (1, self.arguments.max_length))
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/modules/mistral/modelling_mistral_flax.py", line 516, in init_weights
    module_init_outputs = self.module.init(rng_s, input_ids, attention_mask, position_ids, return_dict=False)
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/modules/mistral/modelling_mistral_flax.py", line 807, in __call__
    outputs = self.model(
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/modules/mistral/modelling_mistral_flax.py", line 731, in __call__
    outputs = self.layers(
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/modules/mistral/modelling_mistral_flax.py", line 653, in __call__
    output = layer(
  File "/usr/local/lib/python3.10/dist-packages/flax/linen/partitioning.py", line 553, in inner
    return rematted(variable_groups, rng_groups, *dyn_args)
  File "/usr/local/lib/python3.10/dist-packages/flax/linen/partitioning.py", line 550, in rematted
    y = fn(scope, *args)
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/modules/mistral/modelling_mistral_flax.py", line 454, in __call__
    attention_output = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/modules/mistral/modelling_mistral_flax.py", line 388, in __call__
    attention_mask = nn.combine_masks(attention_mask, causal_mask)
  File "/usr/local/lib/python3.10/dist-packages/flax/linen/attention.py", line 518, in combine_masks
    mask = jnp.logical_and(mask, other_mask)
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/numpy/ufuncs.py", line 136, in op
    return bitwise_op(*promote_args(np_op.__name__, *args))
TypeError: and got incompatible shapes for broadcasting: (1, 1, 1, 8192), (1, 1, 4096, 4096).
```

**Comment by JinSeoungwoo** [comment]
> fix <3

Thank you for fixing error. But I got this error when training on tpu pod

```
Traceback (most recent call last):
  File "/root/tune.py", line 249, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/root/tune.py", line 239, in main
    output = trainer.train(
  File "/usr/local/lib/python3.10/dist-packages/EasyDel/trainer/fsdp_train.py", line 427, in train
    'perplexity': jnp.exp(loss).tolist(),
RuntimeError: Running operations on `Array`s that are not fully addressable by this process (i.e. `Array`s with data sharded across multiple devices and processes.) is dangerous. It’s very important that all processes run the same cross-process computations in the same order otherwise it can lead to hangs. If you’re not already familiar with JAX’s multi-process programming model, please read https://jax.readthedocs.io/en/latest/multi_process.html. To fix this error, run your `jitted` computation inside `with jax.spmd_mode('allow_all'):` context manager.

```

**Comment by JinSeoungwoo** [comment]
> > fix <3
> 
> Thank you for fixing error. But I got this error when training on tpu pod
> 
> ```
> Traceback (most recent call last):
>   File "/root/tune.py", line 249, in <module>
>     app.run(main)
>   File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "/root/tune.py", line 239, in main
>     output = trainer.train(
>   File "/usr/local/lib/python3.10/dist-packages/EasyDel/trainer/fsdp_train.py", line 427, in train
>     'perplexity': jnp.exp(loss).tolist(),
> RuntimeError: Running operations on `Array`s that are not fully addressable by this process (i.e. `Array`s with data sharded across multiple devices and processes.) is dangerous. It’s very important that all processes run the same cross-process computations in the same order otherwise it can lead to hangs. If you’re not already familiar with JAX’s multi-process programming model, please read https://jax.readthedocs.io/en/latest/multi_process.html. To fix this error, run your `jitted` computation inside `with jax.spmd_mode('allow_all'):` context manager.
> ```

Fixed by adding with jax.spmd_mode('allow_all'):

```python
with jax.spmd_mode('allow_all'):
                                    self.wandb_runtime.log(
                                        {
                                            'loss': loss.tolist(),
                                            'learning_rate': self.scheduler(sharded_train_state_.step.tolist()).tolist(),
                                            'step': sharded_train_state_.step.tolist(),
                                            'step time': ttl_time,
                                            'perplexity': jnp.exp(loss).tolist(),
                                            'accuracy': accuracy.tolist(),
                                            'avg_accuracy': (sum(accuracies) / len(accuracies)).tolist(),
                                            'mem_res': mem_res
                                        }
                                    )
```

**Comment by erfanzar** [comment]
thank you for sharing the code but are you sure the code is working fine for training (MistralTrain)
the model works fine on the interface but in training, after five steps the loss value will rise from 1.05648 to 4.~

**Comment by erfanzar** [comment]
![image](https://github.com/erfanzar/EasyDeL/assets/59269023/1f53a5e0-b5ef-4655-90d6-5924e99ae34a)

**Comment by JinSeoungwoo** [comment]
> thank you for sharing the code but are you sure the code is working fine for training (MistralTrain)
> the model works fine on the interface but in training, after five steps the loss value will rise from 1.05648 to 4.~

I don't know if the code I posted is appropriate, but it worked fine in my training, so I used it. Do you think I should restart the training with the updated EasyDeL?

**Comment by erfanzar** [comment]
> > thank you for sharing the code but are you sure the code is working fine for training (MistralTrain)
> > the model works fine on the interface but in training, after five steps the loss value will rise from 1.05648 to 4.~
> 
> I don't know if the code I posted is appropriate, but it worked fine in my training, so I used it. Do you think I should restart the training with the updated EasyDeL?

can you give me more information something like screenshot of W&B process (Loss and Perplexity Only)

**Comment by JinSeoungwoo** [comment]
> can you give me more information something like screenshot of W&B process (Loss and Perplexity Only)

![캡처](https://github.com/erfanzar/EasyDeL/assets/145985028/5fb40dfa-cf70-4c6e-9d9d-3ed1d6073fc8)

Here's a picture of loss and perplexity

**Comment by erfanzar** [comment]
yes you can continue training in case that you haven't see loss higher than 7.~ for more than 10 steps

**Comment by JinSeoungwoo** [comment]
Is it possible to save the model in the save step only on the main node and put it on the huggingface repo?
I edited code to do it

```python
if jax.process_index() == 0
```

but when it was save step, all training was stopped and not progressing.

**Comment by erfanzar** [comment]
> Is it possible to save the model in the save step only on the main node and put it on the huggingface repo? I edited code to do it
> 
> ```python
> if jax.process_index() == 0
> ```
> 
> but when it was save step, all training was stopped and not progressing.

this will cause an error and make other threads or nodes dump so in case that you want to do something like this you should put other nodes to sleep or lock them and you can write a simple script that checks if the new ckpt is saved push that to the hugging face repo

**Comment by JinSeoungwoo** [comment]
> > Is it possible to save the model in the save step only on the main node and put it on the huggingface repo? I edited code to do it
> > 
> > ```python
> > if jax.process_index() == 0
> > ```
> > 
> > but when it was save step, all training was stopped and not progressing.
> 
> this will cause an error and make other threads or nodes dump so in case that you want to do something like this you should put other nodes to sleep or lock them and you can write a simple script that checks if the new ckpt is saved push that to the hugging face repo
> 

Thank you for the advice I fixed it!
