### ISSUE TITLE
How to run llama in the examples

### ISSUE THREAD

**Issue by zigzagcai** [erfanzar/EasyDeL#47]
Hi, I am trying to use EasyDel to democratize LLaMa, but I cannot find guide about how to run this model.
Could you please give me some hint about the EasyDel LLaMa launch script, such as `repo_id` and `dataset_name`? Thanks!

**Comment by erfanzar** [comment]
yes for sure

[Llama Models Serving Documents](https://erfanzar.github.io/EasyDeL/docs/Python/Llama2)

and in case you want to pre-train fine-tune a model or maybe use RL-HF I'm creating a tutorial for that Right Now

**Comment by erfanzar** [comment]
here you go

[Training Example](https://erfanzar.github.io/EasyDeL/docs/Python/TrainingExample)

**Comment by zigzagcai** [comment]
> here you go
> 
> [Training Example](https://erfanzar.github.io/EasyDeL/docs/Python/TrainingExample)

Thanks! Just another question about the dataset.
I see in the docs `dataset_train = load_dataset('REPO_ID_PATH_TO_DATASET')`, but could you give an example of such `REPO_ID_PATH_TO_DATASET`?

**Comment by erfanzar** [comment]
yes [here](https://github.com/erfanzar/EasyDeL/blob/main/docs/Python/DataProcessing.md) you can see an example for how to preprocess data for EasyDel Trainer but you need to install the library from pip+git cause I have added this right now and it's now supported via when you install package via `pip install EasyDel`

```shell
pip install git+https://github.com/erfanzar/EasyDeL.git
```

**Comment by zigzagcai** [comment]
I am sorry I still have some confusion.
Sicne the readme indicates that flash_attn is implemented, I want to know how flash attention is implemented on llama. I don't find codes about flash_attn.

**Comment by erfanzar** [comment]
actually, EasyDel for some parts is only a Code Stand for the Backend of EasyDel

some process like
 - partitioning
 - Linen Bits
 - Flash Attention
 - optimizers

and many more being processed in [FJFormer](https://github.com/erfanzar/FJFormer)

and [here's](https://github.com/erfanzar/FJFormer/blob/main/fjformer/attention/efficient_attention.py) (EfficientAttention) what I guess you looking for

**Comment by zigzagcai** [comment]
I got it. Thanks @erfanzar !
You did awesome work!
