### ISSUE TITLE
Kaggle issue

### ISSUE THREAD

**Issue by infamix** [erfanzar/EasyDeL#59]
Hello, so I am having an issue running EasyDel on Kaggle TPUs, namely, that the jupyter kernel dies while importing the libraries.

**Comment by erfanzar** [comment]
```shell
!pip install jax[tpu]==0.4.17 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html -U -q
!pip install tensorflow --upgrade -q
```

use this and the issue will be fixed

**Comment by infamix** [comment]
> ```shell
> !pip install jax[tpu]==0.4.17 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html -U -q
> !pip install tensorflow --upgrade -q
> ```
> 
> use this and the issue will be fixed

I think I was missing the tensorflow upgrade. 
Trying it right now.
