### ISSUE TITLE
Inference on Single Node multiple GPUs

### ISSUE THREAD

**Issue by clintg6** [erfanzar/EasyDeL#82]
Hi Erfan, how can we load a large model with weights split across multiple GPUs? All of the examples I looked at only show CPU memory offloading.

**Comment by erfanzar** [comment]
Ill create an example for you in next commit but simply you just have to give the shard-fns to loaders

**Comment by erfanzar** [comment]
https://github.com/erfanzar/EasyDeL/blob/main/examples/load_model_parallel.py

**Comment by clintg6** [comment]
This doesn't work. I tried this with Llama-2 and Mixtral and it produces these kind of errors: 
TypeError: MixtralForCausalLM.__init__() got an unexpected keyword argument 'shard_fns'

**Comment by clintg6** [comment]
![image](https://github.com/erfanzar/EasyDeL/assets/7388379/6d84903a-3f71-4230-9dc8-6404993ae238)
Did some digging for some reason for the Mixtral model **params_shape_tree** is empty which forces match_partition_rules to produce an empty Dict and consequently an empty shard_fns. This is not the case when I run Llama2 model. Any idea why it's not producing params_shape_tree for Mixtral but does for Llama-2?

**Comment by erfanzar** [comment]
The trick that we used for shard llama model wont work only and only on mixtral models for that you should use some other tricks

**Comment by erfanzar** [comment]
It's because MoE models are way too dynamic for jax so we cant pass them to jax.eval

**Comment by erfanzar** [comment]
sharding model now fixed on _Mixtral_ models and you can do the same with the just like what you llama for sharding model

**Comment by clintg6** [comment]
I tested **load_model_parallel_llama.py** and it's not working with Mixtral. Works as expected with LlamaStory/Llama-2

Here's the error I'm getting:
![image](https://github.com/erfanzar/EasyDeL/assets/7388379/225cbb82-2583-4e0a-9739-e5dbb51075dc)

**Comment by erfanzar** [comment]
Mixtral models are not compatible with phit again and im tryin to fix moe part but ill create autoshard function in easy api seems like a lot of people want to use this api

**Comment by erfanzar** [comment]
check this out for [easier api call](https://github.com/erfanzar/EasyDeL/blob/main/examples/load_model_parallel_custom_lower_level_api.py)
